<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #111; font-size: 10px; margin: 18px; }
        .header { border-bottom: 2px solid #0d6efd; margin-bottom: 12px; padding-bottom: 8px; }
        h1 { font-size: 18px; margin: 0 0 3px; }
        .muted { color: #666; font-size: 9px; }
        table { border-collapse: collapse; width: 100%; }
        th, td { border: 1px solid #ddd; padding: 5px; text-align: left; }
        th { background: #f5f5f5; }
        .summary { margin: 10px 0 12px; }
        .summary td { width: 25%; }
        .label { color: #666; font-size: 8px; text-transform: uppercase; }
        .value { font-size: 11px; font-weight: bold; }
        .text-end { text-align: right; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <div class="muted">{{ $tenant?->name }} | {{ $branchLabel }} | {{ $dateFrom }} to {{ $dateTo }}</div>
        <div class="muted">Generated by {{ $generatedBy ?? 'System' }} at {{ $generatedAt }}</div>
    </div>

    <table class="summary">
        <tr>
            @foreach ($summary as $label => $value)
                <td>
                    <div class="label">{{ str($label)->headline() }}</div>
                    <div class="value">{{ is_numeric($value) ? number_format((float) $value, 2) : $value }}</div>
                </td>
                @if ($loop->iteration % 4 === 0 && ! $loop->last)
                    </tr><tr>
                @endif
            @endforeach
        </tr>
    </table>

    <table>
        <thead>
            <tr>
                @foreach ($headings as $heading)
                    <th>{{ $heading }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse ($rows as $row)
                <tr>
                    @foreach ($row as $cell)
                        <td @class(['text-end' => is_numeric($cell)])>{{ $cell }}</td>
                    @endforeach
                </tr>
            @empty
                <tr>
                    <td colspan="{{ count($headings) }}" class="muted">No records found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>
