<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body { font-family: Arial, sans-serif; color: #111827; margin: 24px; }
        .header { border-bottom: 2px solid #0d6efd; margin-bottom: 16px; padding-bottom: 12px; }
        h1 { font-size: 22px; margin: 0 0 4px; }
        .muted { color: #6b7280; font-size: 12px; }
        .summary { display: table; width: 100%; margin: 16px 0; border-spacing: 8px; }
        .summary-card { display: table-cell; border: 1px solid #e5e7eb; padding: 10px; }
        .summary-label { color: #6b7280; font-size: 11px; text-transform: uppercase; }
        .summary-value { font-size: 16px; font-weight: 700; margin-top: 4px; }
        table { border-collapse: collapse; width: 100%; font-size: 12px; }
        th, td { border: 1px solid #e5e7eb; padding: 7px; text-align: left; }
        th { background: #f3f4f6; }
        .text-end { text-align: right; }
        .actions { margin-bottom: 14px; }
        .actions button { padding: 8px 12px; }
        @media print {
            .actions { display: none; }
            body { margin: 10mm; }
        }
    </style>
</head>
<body>
    <div class="actions">
        <button type="button" onclick="window.print()">Print</button>
    </div>

    <div class="header">
        <h1>{{ $title }}</h1>
        <div class="muted">{{ $tenant?->name }} | {{ $branchLabel }} | {{ $dateFrom }} to {{ $dateTo }}</div>
        <div class="muted">Generated by {{ $generatedBy ?? 'System' }} at {{ $generatedAt }}</div>
    </div>

    <div class="summary">
        @foreach ($summary as $label => $value)
            <div class="summary-card">
                <div class="summary-label">{{ str($label)->headline() }}</div>
                <div class="summary-value">{{ is_numeric($value) ? number_format((float) $value, 2) : $value }}</div>
            </div>
        @endforeach
    </div>

    <table>
        <thead>
            <tr>
                @foreach ($headings as $heading)
                    <th>{{ $heading }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse ($rows as $row)
                <tr>
                    @foreach ($row as $cell)
                        <td @class(['text-end' => is_numeric($cell)])>{{ $cell }}</td>
                    @endforeach
                </tr>
            @empty
                <tr>
                    <td colspan="{{ count($headings) }}" class="muted">No records found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>
